import type { WheelConfig, WheelBranding, GameType } from '@/lib/types';

export interface WheelTemplate {
  id: string;
  name: string;
  description: string;
  emoji: string;
  /** Which game type this template applies to. */
  gameType: GameType;
  config: Partial<WheelConfig>;
  branding: Partial<WheelBranding>;
  /** Default segment colors (cycled for however many segments exist) */
  segmentPalette: Array<{ bg_color: string; text_color: string }>;
}

// ─── Spin Wheel Templates ─────────────────────────────────────────────────────

export const WHEEL_TEMPLATES: WheelTemplate[] = [
  {
    id: 'freepik-gold-test',
    name: 'Freepik Gold Test',
    description: 'Ultra Premium 3D Golden Wheel with separated PNG layers (Image Mode)',
    emoji: '⭐',
    gameType: 'wheel',
    config: {
      animation_speed: 'medium',
      show_segment_labels: true,
      sound_enabled: true,
    },
    branding: {
      primary_color: '#B8860B', // Metallic Gold
      secondary_color: '#000000', // Deep Black
      background_type: 'solid',
      background_value: 'rgba(0, 0, 0, 0)', // Transparent
      font_family: 'Bebas Neue', // Common for this style
      button_text: 'SPIN NOW',
      button_color: '#D4AF37',
      // The keys that bypass math rendering
      premium_face_url: '/assets/premium-wheels/Wheel.png',
      premium_stand_url: '/assets/premium-wheels/Stand.png',
      premium_content_scale: 0.65, // Adjusts text and icons to fit within the golden center
      
      // Hide standard features
      outer_ring_width: 0,
      inner_ring_enabled: false,
      border_width: 0,
      rim_tick_style: 'none',
      label_font_size: undefined,
      label_position: 'inner',
      label_font_weight: '800', // Make labels bold
    },
    segmentPalette: [
      // Standard segment colours that would match what we want labels to do
      // Here bg is 'transparent' so no math segments draw properly OR the renderer ignores bg when premium_img exists.
      { bg_color: 'transparent', text_color: '#FFFFFF' },
      { bg_color: 'transparent', text_color: '#000000' },
      { bg_color: 'transparent', text_color: '#FFFFFF' },
      { bg_color: 'transparent', text_color: '#000000' },
    ],
  },
  {
    id: 'luxury-gold',

    gameType: 'wheel',
    name: 'Luxury Gold',
    description: 'Elegant black & gold premium feel',
    emoji: '🏆',
    config: { show_segment_labels: true, confetti_enabled: true },
    branding: {
      primary_color: '#B8860B',
      outer_ring_color: '#B8860B',
      outer_ring_width: 28,
      rim_tick_style: 'triangles',
      rim_tick_color: '#FFD700',
      inner_ring_enabled: true,
      inner_ring_color: 'rgba(255,215,0,0.20)',
      button_text: 'SPIN TO WIN',
      background_value: '#0D0D0D',
    },
    segmentPalette: [
      { bg_color: '#1A1A1A', text_color: '#FFD700' },
      { bg_color: '#B8860B', text_color: '#000000' },
      { bg_color: '#2A2A2A', text_color: '#FFC000' },
      { bg_color: '#DAA520', text_color: '#1A1A1A' },
      { bg_color: '#111111', text_color: '#FFE066' },
      { bg_color: '#C9A84C', text_color: '#000000' },
    ],
  },
  {
    id: 'neon-night',
    gameType: 'wheel',
    name: 'Neon Night',
    description: 'Dark background with electric neon accents',
    emoji: '🌃',
    config: { show_segment_labels: true, confetti_enabled: true },
    branding: {
      primary_color: '#FF00FF',
      outer_ring_color: '#7B00FF',
      outer_ring_width: 24,
      rim_tick_style: 'dots',
      rim_tick_color: '#00FFFF',
      inner_ring_enabled: true,
      inner_ring_color: 'rgba(0,255,255,0.15)',
      button_text: 'SPIN!',
      background_value: '#0A0A0F',
    },
    segmentPalette: [
      { bg_color: '#1A0030', text_color: '#FF00FF' },
      { bg_color: '#000D30', text_color: '#00FFFF' },
      { bg_color: '#1A0030', text_color: '#FF6FD8' },
      { bg_color: '#000D30', text_color: '#39FF14' },
      { bg_color: '#1A0030', text_color: '#FFE600' },
      { bg_color: '#000D30', text_color: '#FF4500' },
    ],
  },
  {
    id: 'ocean-blue',
    gameType: 'wheel',
    name: 'Ocean Blue',
    description: 'Cool blues and teals for a calm, trustworthy feel',
    emoji: '🌊',
    config: { show_segment_labels: true, confetti_enabled: true },
    branding: {
      primary_color: '#0077B6',
      outer_ring_color: '#023E8A',
      outer_ring_width: 22,
      rim_tick_style: 'triangles',
      rim_tick_color: '#90E0EF',
      inner_ring_enabled: false,
      button_text: 'SPIN THE WHEEL',
      background_value: '#CAF0F8',
    },
    segmentPalette: [
      { bg_color: '#023E8A', text_color: '#FFFFFF' },
      { bg_color: '#0077B6', text_color: '#FFFFFF' },
      { bg_color: '#0096C7', text_color: '#FFFFFF' },
      { bg_color: '#00B4D8', text_color: '#FFFFFF' },
      { bg_color: '#48CAE4', text_color: '#023E8A' },
      { bg_color: '#90E0EF', text_color: '#023E8A' },
    ],
  },
  {
    id: 'pastel-spring',
    gameType: 'wheel',
    name: 'Pastel Spring',
    description: 'Soft pastel palette — light, friendly, and fun',
    emoji: '🌸',
    config: { show_segment_labels: true, confetti_enabled: true },
    branding: {
      primary_color: '#F48FB1',
      outer_ring_color: '#CE93D8',
      outer_ring_width: 20,
      rim_tick_style: 'dots',
      rim_tick_color: '#FFFFFF',
      inner_ring_enabled: false,
      button_text: 'Try Your Luck!',
      background_value: '#FFF0F5',
    },
    segmentPalette: [
      { bg_color: '#FFB3C6', text_color: '#5C2D4A' },
      { bg_color: '#B5EAD7', text_color: '#1E4D3A' },
      { bg_color: '#C7CEEA', text_color: '#2D3561' },
      { bg_color: '#FFE4BA', text_color: '#5C3A00' },
      { bg_color: '#FFDAC1', text_color: '#5C2400' },
      { bg_color: '#E2F0CB', text_color: '#2E4B0A' },
    ],
  },
  {
    id: 'fire-ice',
    gameType: 'wheel',
    name: 'Fire & Ice',
    description: 'Alternating red-hot and ice-cool contrast',
    emoji: '🔥',
    config: { show_segment_labels: true, confetti_enabled: true },
    branding: {
      primary_color: '#FF4500',
      outer_ring_color: '#FF6B35',
      outer_ring_width: 26,
      rim_tick_style: 'triangles',
      rim_tick_color: '#FFFFFF',
      inner_ring_enabled: true,
      inner_ring_color: 'rgba(255,255,255,0.12)',
      button_text: 'SPIN NOW!',
      background_value: '#FFFFFF',
    },
    segmentPalette: [
      { bg_color: '#FF4500', text_color: '#FFFFFF' },
      { bg_color: '#00B4D8', text_color: '#FFFFFF' },
      { bg_color: '#FF6B35', text_color: '#FFFFFF' },
      { bg_color: '#0077B6', text_color: '#FFFFFF' },
      { bg_color: '#FF8C42', text_color: '#FFFFFF' },
      { bg_color: '#48CAE4', text_color: '#023E8A' },
    ],
  },
  {
    id: 'corporate',
    gameType: 'wheel',
    name: 'Corporate',
    description: 'Professional blues and greys for B2B brands',
    emoji: '💼',
    config: { show_segment_labels: true, confetti_enabled: false },
    branding: {
      primary_color: '#1E3A5F',
      outer_ring_color: '#1E3A5F',
      outer_ring_width: 20,
      rim_tick_style: 'none',
      inner_ring_enabled: false,
      button_text: 'Spin the Wheel',
      background_value: '#F8FAFC',
    },
    segmentPalette: [
      { bg_color: '#1E3A5F', text_color: '#FFFFFF' },
      { bg_color: '#2C5282', text_color: '#FFFFFF' },
      { bg_color: '#3B6CB7', text_color: '#FFFFFF' },
      { bg_color: '#4A90D9', text_color: '#FFFFFF' },
      { bg_color: '#64B5F6', text_color: '#1E3A5F' },
      { bg_color: '#BBDEFB', text_color: '#1E3A5F' },
    ],
  },
  {
    id: 'tropical',
    gameType: 'wheel',
    name: 'Tropical',
    description: 'Bright tropical colours — summer vibes',
    emoji: '🌴',
    config: { show_segment_labels: true, confetti_enabled: true },
    branding: {
      primary_color: '#FF6F00',
      outer_ring_color: '#F9A825',
      outer_ring_width: 22,
      rim_tick_style: 'dots',
      rim_tick_color: '#FFFFFF',
      inner_ring_enabled: false,
      button_text: 'SPIN!',
      background_value: '#E8F5E9',
    },
    segmentPalette: [
      { bg_color: '#FF6F00', text_color: '#FFFFFF' },
      { bg_color: '#2E7D32', text_color: '#FFFFFF' },
      { bg_color: '#F9A825', text_color: '#1A1A1A' },
      { bg_color: '#00838F', text_color: '#FFFFFF' },
      { bg_color: '#E64A19', text_color: '#FFFFFF' },
      { bg_color: '#558B2F', text_color: '#FFFFFF' },
    ],
  },
  {
    id: 'festival',
    gameType: 'wheel',
    name: 'Festival',
    description: 'Vibrant multicolour — celebrate every spin',
    emoji: '🎉',
    config: { show_segment_labels: true, confetti_enabled: true },
    branding: {
      primary_color: '#7C3AED',
      outer_ring_color: '#7C3AED',
      outer_ring_width: 24,
      rim_tick_style: 'triangles',
      rim_tick_color: '#FFFFFF',
      inner_ring_enabled: true,
      inner_ring_color: 'rgba(255,255,255,0.15)',
      button_text: 'SPIN TO WIN!',
      background_value: '#FFFFFF',
    },
    segmentPalette: [
      { bg_color: '#E74C3C', text_color: '#FFFFFF' },
      { bg_color: '#3498DB', text_color: '#FFFFFF' },
      { bg_color: '#2ECC71', text_color: '#FFFFFF' },
      { bg_color: '#F39C12', text_color: '#FFFFFF' },
      { bg_color: '#9B59B6', text_color: '#FFFFFF' },
      { bg_color: '#1ABC9C', text_color: '#FFFFFF' },
      { bg_color: '#E67E22', text_color: '#FFFFFF' },
      { bg_color: '#2980B9', text_color: '#FFFFFF' },
    ],
  },

  // ─── Scratch Card Templates ─────────────────────────────────────────────────

  {
    id: 'scratch-golden-ticket',
    gameType: 'scratch_card',
    name: 'Golden Ticket',
    description: 'Classic lottery gold — premium metallic feel',
    emoji: '🥇',
    config: {
      scratch_layer_style: 'metallic',
      scratch_layer_color: '#C9A84C',
      scratch_card_layout: 'single',
      scratch_card_size: 'large',
      scratch_border_color: '#B8860B',
      scratch_border_radius: 12,
      scratch_reveal_threshold: 0.5,
    },
    branding: {
      primary_color: '#B8860B',
      button_text: 'Scratch to Win!',
      background_value: '#FFF8E1',
      font_family: 'Georgia, serif',
    },
    segmentPalette: [
      { bg_color: '#1A1A1A', text_color: '#FFD700' },
      { bg_color: '#B8860B', text_color: '#000000' },
      { bg_color: '#DAA520', text_color: '#1A1A1A' },
      { bg_color: '#C9A84C', text_color: '#000000' },
    ],
  },
  {
    id: 'scratch-rainbow-foil',
    gameType: 'scratch_card',
    name: 'Rainbow Foil',
    description: 'Iridescent foil layer — eye-catching and modern',
    emoji: '🌈',
    config: {
      scratch_layer_style: 'foil',
      scratch_card_layout: 'grid_2x2',
      scratch_card_size: 'large',
      scratch_border_color: '#7C3AED',
      scratch_border_radius: 20,
      scratch_reveal_threshold: 0.55,
    },
    branding: {
      primary_color: '#7C3AED',
      button_text: 'Reveal Your Prize!',
      background_value: '#F5F0FF',
    },
    segmentPalette: [
      { bg_color: '#7C3AED', text_color: '#FFFFFF' },
      { bg_color: '#EC4899', text_color: '#FFFFFF' },
      { bg_color: '#06B6D4', text_color: '#FFFFFF' },
      { bg_color: '#10B981', text_color: '#FFFFFF' },
    ],
  },
  {
    id: 'scratch-silver-classic',
    gameType: 'scratch_card',
    name: 'Silver Classic',
    description: 'Traditional grey scratch card — familiar lottery feel',
    emoji: '🪙',
    config: {
      scratch_layer_style: 'solid',
      scratch_layer_color: '#9E9E9E',
      scratch_card_layout: 'row_3x1',
      scratch_card_size: 'medium',
      scratch_border_color: '#616161',
      scratch_border_radius: 8,
      scratch_reveal_threshold: 0.6,
    },
    branding: {
      primary_color: '#424242',
      button_text: 'Scratch & Win',
      background_value: '#FAFAFA',
    },
    segmentPalette: [
      { bg_color: '#E53935', text_color: '#FFFFFF' },
      { bg_color: '#1E88E5', text_color: '#FFFFFF' },
      { bg_color: '#43A047', text_color: '#FFFFFF' },
      { bg_color: '#FB8C00', text_color: '#FFFFFF' },
    ],
  },
  {
    id: 'scratch-neon-reveal',
    gameType: 'scratch_card',
    name: 'Neon Reveal',
    description: 'Dark card with neon glow — night-out energy',
    emoji: '💜',
    config: {
      scratch_layer_style: 'striped',
      scratch_layer_color: '#1A0030',
      scratch_card_layout: 'single',
      scratch_card_size: 'large',
      scratch_border_color: '#FF00FF',
      scratch_border_radius: 20,
      scratch_reveal_threshold: 0.5,
    },
    branding: {
      primary_color: '#FF00FF',
      button_text: 'REVEAL!',
      background_value: '#0A0A0F',
    },
    segmentPalette: [
      { bg_color: '#1A0030', text_color: '#FF00FF' },
      { bg_color: '#000D30', text_color: '#00FFFF' },
      { bg_color: '#1A1A00', text_color: '#FFE600' },
      { bg_color: '#001A00', text_color: '#39FF14' },
    ],
  },
  {
    id: 'scratch-summer-fun',
    gameType: 'scratch_card',
    name: 'Summer Fun',
    description: 'Bright striped card — playful and energetic',
    emoji: '☀️',
    config: {
      scratch_layer_style: 'striped',
      scratch_layer_color: '#FF6F00',
      scratch_card_layout: 'grid_2x2',
      scratch_card_size: 'medium',
      scratch_border_color: '#F9A825',
      scratch_border_radius: 24,
      scratch_reveal_threshold: 0.65,
    },
    branding: {
      primary_color: '#FF6F00',
      button_text: 'Scratch to Reveal!',
      background_value: '#FFFDE7',
    },
    segmentPalette: [
      { bg_color: '#FF6F00', text_color: '#FFFFFF' },
      { bg_color: '#2E7D32', text_color: '#FFFFFF' },
      { bg_color: '#F9A825', text_color: '#1A1A1A' },
      { bg_color: '#00838F', text_color: '#FFFFFF' },
    ],
  },
  {
    id: 'scratch-minimal-white',
    gameType: 'scratch_card',
    name: 'Minimal White',
    description: 'Clean, modern card for premium brands',
    emoji: '🤍',
    config: {
      scratch_layer_style: 'solid',
      scratch_layer_color: '#E0E0E0',
      scratch_card_layout: 'single',
      scratch_card_size: 'medium',
      scratch_border_color: '#9E9E9E',
      scratch_border_radius: 16,
      scratch_reveal_threshold: 0.7,
    },
    branding: {
      primary_color: '#1E3A5F',
      button_text: 'Reveal Prize',
      background_value: '#FFFFFF',
      font_family: 'Inter, sans-serif',
    },
    segmentPalette: [
      { bg_color: '#1E3A5F', text_color: '#FFFFFF' },
      { bg_color: '#3B6CB7', text_color: '#FFFFFF' },
      { bg_color: '#64B5F6', text_color: '#1E3A5F' },
      { bg_color: '#BBDEFB', text_color: '#1E3A5F' },
    ],
  },

  // ─── Slot Machine Templates ─────────────────────────────────────────────────

  {
    id: 'slot-vegas-classic',
    gameType: 'slot_machine',
    name: 'Vegas Classic',
    description: 'Old-school red cabinet with gold trim — casino vibes',
    emoji: '🎰',
    config: {
      slot_reel_count: 3,
      slot_visible_rows: 3,
      slot_symbol_mode: 'both',
      slot_cabinet_style: 'classic',
      slot_spin_duration_ms: 3500,
      slot_stop_delay_ms: 700,
      slot_win_line_color: '#F39C12',
    },
    branding: {
      primary_color: '#C0392B',
      button_text: 'PULL!',
      background_value: '#1A0A00',
      font_family: 'Georgia, serif',
    },
    segmentPalette: [
      { bg_color: '#C0392B', text_color: '#FFD700' },
      { bg_color: '#1A0A00', text_color: '#F39C12' },
      { bg_color: '#8B0000', text_color: '#FFD700' },
      { bg_color: '#2C1A00', text_color: '#FFC107' },
      { bg_color: '#A52A2A', text_color: '#FFEB3B' },
      { bg_color: '#3C1414', text_color: '#FFD700' },
    ],
  },
  {
    id: 'slot-neon-tokyo',
    gameType: 'slot_machine',
    name: 'Neon Tokyo',
    description: 'Dark neon cabinet with electric glow effects',
    emoji: '🗼',
    config: {
      slot_reel_count: 3,
      slot_visible_rows: 3,
      slot_symbol_mode: 'both',
      slot_cabinet_style: 'neon',
      slot_spin_duration_ms: 3000,
      slot_stop_delay_ms: 500,
      slot_win_line_color: '#00FFFF',
    },
    branding: {
      primary_color: '#FF00FF',
      button_text: 'SPIN!',
      background_value: '#0A0A0F',
    },
    segmentPalette: [
      { bg_color: '#1A0030', text_color: '#FF00FF' },
      { bg_color: '#000D30', text_color: '#00FFFF' },
      { bg_color: '#1A1A00', text_color: '#FFE600' },
      { bg_color: '#001A00', text_color: '#39FF14' },
      { bg_color: '#1A0010', text_color: '#FF6FD8' },
      { bg_color: '#001A1A', text_color: '#7DF9FF' },
    ],
  },
  {
    id: 'slot-gold-rush',
    gameType: 'slot_machine',
    name: 'Gold Rush',
    description: 'Modern flat cabinet in warm gold and amber',
    emoji: '✨',
    config: {
      slot_reel_count: 5,
      slot_visible_rows: 3,
      slot_symbol_mode: 'both',
      slot_cabinet_style: 'modern',
      slot_spin_duration_ms: 4000,
      slot_stop_delay_ms: 600,
      slot_win_line_color: '#FFD700',
    },
    branding: {
      primary_color: '#B8860B',
      button_text: 'SPIN TO WIN!',
      background_value: '#FFF8E1',
    },
    segmentPalette: [
      { bg_color: '#1A1A1A', text_color: '#FFD700' },
      { bg_color: '#B8860B', text_color: '#000000' },
      { bg_color: '#2A2A2A', text_color: '#FFC000' },
      { bg_color: '#DAA520', text_color: '#1A1A1A' },
      { bg_color: '#111111', text_color: '#FFE066' },
    ],
  },
  {
    id: 'slot-ocean-deep',
    gameType: 'slot_machine',
    name: 'Ocean Deep',
    description: 'Calm blue modern cabinet — trustworthy and clean',
    emoji: '🌊',
    config: {
      slot_reel_count: 3,
      slot_visible_rows: 1,
      slot_symbol_mode: 'icon',
      slot_cabinet_style: 'modern',
      slot_spin_duration_ms: 2500,
      slot_stop_delay_ms: 400,
      slot_win_line_color: '#00B4D8',
    },
    branding: {
      primary_color: '#0077B6',
      button_text: 'Spin the Slots',
      background_value: '#CAF0F8',
    },
    segmentPalette: [
      { bg_color: '#023E8A', text_color: '#FFFFFF' },
      { bg_color: '#0077B6', text_color: '#FFFFFF' },
      { bg_color: '#0096C7', text_color: '#FFFFFF' },
      { bg_color: '#00B4D8', text_color: '#FFFFFF' },
      { bg_color: '#48CAE4', text_color: '#023E8A' },
    ],
  },
  {
    id: 'slot-fruit-party',
    gameType: 'slot_machine',
    name: 'Fruit Party',
    description: 'Classic fruit machine colours — nostalgic and fun',
    emoji: '🍒',
    config: {
      slot_reel_count: 3,
      slot_visible_rows: 3,
      slot_symbol_mode: 'both',
      slot_cabinet_style: 'classic',
      slot_spin_duration_ms: 3000,
      slot_stop_delay_ms: 600,
      slot_win_line_color: '#F39C12',
    },
    branding: {
      primary_color: '#E74C3C',
      button_text: 'SPIN!',
      background_value: '#FFFFFF',
    },
    segmentPalette: [
      { bg_color: '#E74C3C', text_color: '#FFFFFF' },
      { bg_color: '#F39C12', text_color: '#FFFFFF' },
      { bg_color: '#2ECC71', text_color: '#FFFFFF' },
      { bg_color: '#3498DB', text_color: '#FFFFFF' },
      { bg_color: '#9B59B6', text_color: '#FFFFFF' },
      { bg_color: '#1ABC9C', text_color: '#FFFFFF' },
    ],
  },
  {
    id: 'slot-minimal-5reel',
    gameType: 'slot_machine',
    name: 'Big Five',
    description: '5-reel modern layout — maximum excitement',
    emoji: '5️⃣',
    config: {
      slot_reel_count: 5,
      slot_visible_rows: 3,
      slot_symbol_mode: 'label',
      slot_cabinet_style: 'modern',
      slot_spin_duration_ms: 4500,
      slot_stop_delay_ms: 500,
      slot_win_line_color: '#7C3AED',
    },
    branding: {
      primary_color: '#7C3AED',
      button_text: 'SPIN ALL 5!',
      background_value: '#F5F0FF',
    },
    segmentPalette: [
      { bg_color: '#7C3AED', text_color: '#FFFFFF' },
      { bg_color: '#EC4899', text_color: '#FFFFFF' },
      { bg_color: '#06B6D4', text_color: '#FFFFFF' },
      { bg_color: '#10B981', text_color: '#FFFFFF' },
      { bg_color: '#F59E0B', text_color: '#FFFFFF' },
      { bg_color: '#EF4444', text_color: '#FFFFFF' },
    ],
  },

  // ─── Roulette Templates ─────────────────────────────────────────────────────

  {
    id: 'roulette-vegas-classic',
    gameType: 'roulette',
    name: 'Vegas Classic',
    description: 'Dark mahogany rim, gold accents — authentic casino feel',
    emoji: '🎰',
    config: {
      roulette_pocket_style: 'classic',
      roulette_spin_duration_ms: 5000,
    },
    branding: {
      primary_color: '#C8A050',
      button_text: 'SPIN!',
      background_value: '#065c20',
      font_family: 'Georgia, serif',
    },
    segmentPalette: [
      { bg_color: '#C0392B', text_color: '#FFFFFF' },
      { bg_color: '#1A1A1A', text_color: '#FFD700' },
      { bg_color: '#C0392B', text_color: '#FFFFFF' },
      { bg_color: '#111111', text_color: '#FFD700' },
      { bg_color: '#C0392B', text_color: '#FFFFFF' },
      { bg_color: '#1A1A1A', text_color: '#FFD700' },
    ],
  },
  {
    id: 'roulette-monte-carlo',
    gameType: 'roulette',
    name: 'Monte Carlo',
    description: 'Elegant European roulette — deep green felt and ivory',
    emoji: '🃏',
    config: {
      roulette_pocket_style: 'classic',
      roulette_spin_duration_ms: 6000,
    },
    branding: {
      primary_color: '#B8860B',
      button_text: 'Place Your Bet',
      background_value: '#1B4332',
      font_family: 'Georgia, serif',
    },
    segmentPalette: [
      { bg_color: '#8B0000', text_color: '#FFF8E1' },
      { bg_color: '#1A2E1A', text_color: '#F5DEB3' },
      { bg_color: '#8B0000', text_color: '#FFF8E1' },
      { bg_color: '#2D4A2D', text_color: '#F5DEB3' },
      { bg_color: '#8B0000', text_color: '#FFF8E1' },
      { bg_color: '#1A2E1A', text_color: '#F5DEB3' },
    ],
  },
  {
    id: 'roulette-neon-tokyo',
    gameType: 'roulette',
    name: 'Neon Tokyo',
    description: 'Cyberpunk roulette — glowing neon on dark canvas',
    emoji: '🌃',
    config: {
      roulette_pocket_style: 'neon',
      roulette_spin_duration_ms: 4500,
    },
    branding: {
      primary_color: '#00FFFF',
      button_text: 'SPIN!',
      background_value: '#0A0A14',
    },
    segmentPalette: [
      { bg_color: '#001A30', text_color: '#00FFFF' },
      { bg_color: '#1A0030', text_color: '#FF00FF' },
      { bg_color: '#001A30', text_color: '#39FF14' },
      { bg_color: '#1A0030', text_color: '#FFE600' },
      { bg_color: '#001A30', text_color: '#FF6FD8' },
      { bg_color: '#1A0030', text_color: '#7DF9FF' },
    ],
  },
  {
    id: 'roulette-neon-purple',
    gameType: 'roulette',
    name: 'Neon Purple',
    description: 'Deep violet glow — electric night club energy',
    emoji: '💜',
    config: {
      roulette_pocket_style: 'neon',
      roulette_spin_duration_ms: 4000,
    },
    branding: {
      primary_color: '#FF00FF',
      button_text: 'SPIN NOW!',
      background_value: '#0A000F',
    },
    segmentPalette: [
      { bg_color: '#1A0030', text_color: '#FF00FF' },
      { bg_color: '#0D001A', text_color: '#BF5FFF' },
      { bg_color: '#1A0030', text_color: '#FF6FD8' },
      { bg_color: '#0D001A', text_color: '#E040FB' },
      { bg_color: '#1A0030', text_color: '#CE93D8' },
      { bg_color: '#0D001A', text_color: '#FF00FF' },
    ],
  },
  {
    id: 'roulette-modern-minimal',
    gameType: 'roulette',
    name: 'Modern Minimal',
    description: 'Clean flat design — premium brand feel',
    emoji: '⚪',
    config: {
      roulette_pocket_style: 'modern',
      roulette_spin_duration_ms: 4500,
    },
    branding: {
      primary_color: '#1E3A5F',
      button_text: 'Spin the Wheel',
      background_value: '#F8FAFC',
      font_family: 'Inter, sans-serif',
    },
    segmentPalette: [
      { bg_color: '#1E3A5F', text_color: '#FFFFFF' },
      { bg_color: '#3B6CB7', text_color: '#FFFFFF' },
      { bg_color: '#4A90D9', text_color: '#FFFFFF' },
      { bg_color: '#64B5F6', text_color: '#1E3A5F' },
      { bg_color: '#BBDEFB', text_color: '#1E3A5F' },
      { bg_color: '#2C5282', text_color: '#FFFFFF' },
    ],
  },
  {
    id: 'roulette-gold-rush',
    gameType: 'roulette',
    name: 'Gold Rush',
    description: 'Warm gold and amber modern cabinet — luxury feel',
    emoji: '✨',
    config: {
      roulette_pocket_style: 'modern',
      roulette_spin_duration_ms: 5500,
    },
    branding: {
      primary_color: '#B8860B',
      button_text: 'SPIN TO WIN!',
      background_value: '#FFF8E1',
    },
    segmentPalette: [
      { bg_color: '#1A1A1A', text_color: '#FFD700' },
      { bg_color: '#B8860B', text_color: '#000000' },
      { bg_color: '#2A2A2A', text_color: '#FFC000' },
      { bg_color: '#DAA520', text_color: '#1A1A1A' },
      { bg_color: '#111111', text_color: '#FFE066' },
      { bg_color: '#C9A84C', text_color: '#000000' },
    ],
  },
];
